services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql

volumes:
  mysql-data:
